app/common/header/Login.js
- 이메일 형식 검증
- 비밀번호 형식 및 비밀번호 일치 여부 검증
- 인증 번호 inputtext, button 생성
- 인증 번호 일치 여부 검증
- 통일감을 위해 입력란 이름 한글로 변경
=> SW-79 feat(login): Add login input validation check

app/diary/list/DateRangePicker.js, app/diary/list/grid/SearchBox.js, app/diary/list/grid/page.jsx, app/diary/list/layout.jsx
- grid와 calendar가 Search box를 공유하고 있었는데, 두 페이지에서 필요한 검색 옵션이 다를 것 같아서 Grid에서만 현재 Search box를 사용하기로 하였습니다.
=> SW-81 feat(diary_search):Set Grid List search data

app/diary/common/Editor.js, app/diary/common/diaryInputFormat.js
- Move Editor.js(Text Editor Component) from "app/common" to "app/diary/common" 
> 일기 작성 및 수정에서만 사용될 것 같아서 diary 디렉토리 안으로 이동
- Add thumbnail image save button
> "이 사진으로 결정" 버튼 클릭 -> 썸네일 저장
> 사진 저장 후 
> => 안내 메세지 변경, 사진 hover effect 제거 및 onClick 비활성화, "저장하기"버튼 활성화
- Added thumbnail image URL code for development (commented out)
=> SW-82 feat(save_thumbnail):Save thumbnail before saving the diary

app/common/header/Login.js
> 자동 로그인 삭제하고 이메일 조회 & 비밀번호 재설정 추가
- 이메일 입력 후 회원 가입 여부 확인 API 호출
- 이메일 입력 후 인증메일 전송 (TODO)
- 비밀번호 입력 후 비밀번호 재설정 API 호출
- 비밀번호 재설정과 회원가입은 같은 모달을 공유하도록 구현함
=> SW-79 feat(login): Add check email & change password function

app/common/header/Profile.js, public/data/user.json
- 프로필 이미지 업로드 기능
- 이름, 비밀번호, 프로필 이미지 수정 기능 (소셜 로그인 사용자인 경우 이름만 수정 가능)
- 로그아웃 버튼 클릭 시 로그아웃 API 요청 기능
- 내 프로필의 총 작성한 일기 수 불러오기
- 프로필 이미지 업로드 기능이 추가되면서 `json`에서 `form-data`로 변경
=> SW-86 feat(profile): Add change profile info & logout

app/common/header/Profile.js
- 기존 하나의 모달에서 두 기능을 수행함
- `유저 정보 업데이트`와 `비밀번호 재설정` api가 각각 존재하기에 두 개의 모달로 분리함
=> SW-86 feat(profile): Modify change profile info & password

app/api/analyzeDiary.js, app/api/deleteDiary.js, app/api/getDiaryList.js, app/diary/[diaryId]/diaryContents.js, app/diary/[diaryId]/modify/page.jsx, app/diary/[diaryId]/page.jsx, app/diary/common/Editor.js, app/diary/dashboard/DiaryCards.js, app/diary/list/calendar/calendarList.js, app/diary/list/calendar/page.jsx, app/diary/list/grid/Pagination.css, app/diary/list/grid/gridList.js, app/diary/list/grid/page.jsx, app/globals.css, app/hooks/mutations/useDiaryDelete.js, app/hooks/queries/useDiaryListPageQuery.js, app/hooks/queries/useDiaryListQuery.js, app/hooks/queries/useDiaryQuery.js, app/hooks/queries/useUserInfoQuery.js, package.json
* Grid List Pagination 추가
* 일기 저장시 발생하는 오류 수정
* 일기 목록 가져오는 react-query 함수 분리 (page 설정을 위함)
=> SW-97 Feature/diary list data

app/api/checkIsMember.js, app/api/checkPassword.js, app/api/getUserInfo.js, app/api/getUserInfoLoginId.js, app/api/login.js, app/api/logout.js, app/api/signUp.js, app/api/updatePassword.js, app/api/updateToken.js, app/api/updateUserInfo.js, app/common/header/Login.js, app/common/header/Profile.js, app/diary/dashboard/UserProfile.js, app/diary/dashboard/page.jsx, app/hooks/mutations/useLogin.js, app/hooks/mutations/useLogout.js, app/hooks/mutations/useTokenUpdate.js, app/hooks/mutations/useUserInfoUpdate.js, app/hooks/queries/useTokenQuery.js, app/hooks/queries/useUserInfoQuery.js, package.json
- updateUserInfo
- checkPassword
- updatePassword
- checkIsMember
- getUserInfoLoginId (추후 삭제 예정)
- login
- signUp
- logout
- updateToken
- useUserInfoUpdate
- useLogin
- useTokenQuery
- useLogin
- useTokenUpdate
- cookies-next
- 로그인 시 `로그인 api` 호출
- 로그인 실패 시 응답 코드에 따라 에러 처리
- 로그인 성공 시 `TOKEN` 쿼리에 토큰 정보 저장
- loginId, userId 기반 `유저 정보 조회 api` 호출하여 쿠키에 `userId` 저장
> TODO: emotion count 값 설정하기
- 회원가입 시 인증 메일 발송 전 `회원 여부 확인 api` 호출 & `회원가입 api` 호출
- 로그아웃 시 `로그인 api` 호출
- `USER_INFO`와 `TOKEN` 쿼리 삭제
- 이메일 조회 시 `회원 여부 확인 api` 호출
- 비밀번호 재설정 시 메일 발송 전 `회원 여부 확인 api` 호출 &` 비밀번호 재설정 api` 호출
- 내 프로필의 이름, 프로필 이미지 수정 시 `유저 정보 업데이트 api` 호출
- `USER_INFO` 쿼리 무효화
> TODO: 프로필 이미지 object storage에 올리기
- 비밀번호 변경 시 `현재 비밀번호 검증 api` 호출 & `비밀번호 재설정 api` 호출
=> SW-97 feat(data-fetching-userInfo): userInfo-related API calls & data fetching

app/api/getUserInfo.js, app/api/updateToken.js, app/api/updateUserInfo.js, app/common/header/Header.jsx, app/common/header/Profile.js, app/diary/dashboard/UserProfile.js, app/diary/dashboard/page.jsx, app/hooks/mutations/useLogin.js, app/hooks/mutations/useTokenUpdate.js, app/hooks/mutations/useUserInfoUpdate.js, app/hooks/queries/useUserInfoQuery.js
1. API 호출할 때 쿠키에서 userId 가져오도록 변경 (getUserInfo, updateUserInfo, updateToken)
2. userId 쿠키 만료 옵션을 Session으로 변경
3. userId 쿠키 존재 여부에 따라 header 설정
1. 로그인 성공 시 refreshToken 쿠키에 저장
=> SW-97 feat(data-fetching-userInfo): Modify cookie-related settings

app/api/deleteDiary.js, app/api/getDiary.js, app/api/getDiaryList.js, app/api/getUserInfo.js, app/common/Drawer.jsx, app/common/header/Header.jsx, app/diary/[diaryId]/diaryContents.js, app/diary/[diaryId]/modify/date.js, app/diary/[diaryId]/modify/page.jsx, app/diary/[diaryId]/page.jsx, app/diary/common/Editor.js, app/diary/common/diaryInputFormat.js, app/diary/common/loading.js, app/diary/dashboard/UserProfile.js, app/diary/dashboard/page.jsx, app/diary/list/calendar/calendarList.js, app/diary/list/calendar/page.jsx, app/diary/list/grid/gridList.js, app/diary/list/grid/page.jsx, app/hooks/mutations/useDiaryDelete.js, app/hooks/mutations/useDiarySave.js, app/hooks/mutations/useLogin.js, app/hooks/queries/useDiaryListQuery.js, app/hooks/queries/useDiaryQuery.js, app/hooks/queries/useUserInfoQuery.js
* API 요청 시 `userId` cookie값 사용
* Server side data fetching 삭제
(해당 부분으로 인해 build 오류 발생 → 우선 삭제. 추후 확인하여 수정 예정)
* `useQuery` initailData 삭제 
* `diary/[diaryId]/modify` 페이지에서 date fetching이 미리 이루어지지 않아 날짜 가져오는 부분 표시 불가능 ⇒ `<date>` 컴포넌트 분리
* `<Header>` component에서 발생하는 Hydration error 처리
* 쿠키값에서 `todayDiaryId` 확인하여 `오늘의 일기 쓰기` 버튼 클릭 이벤트 처리
* `todayDiaryId` 에 diaryId 있을 경우 일기 수정 페이지로 이동 / 비어있을 경우 일기 생성 페이지로 이동
=> SW-124 Build Error Handling

app/common/Drawer.jsx, app/common/header/Login.js, app/common/header/Profile.js, app/diary/[diaryId]/diaryContents.js, app/diary/common/Editor.js, app/diary/common/backButton.js, app/diary/dashboard/UserProfile.js, app/diary/list/calendar/calendarList.js, app/layout.jsx, app/page.jsx
* 로그인 성공시 로그인 modal 닫기 이벤트 추가
* root 화면에 `/home/landing` 페이지로 이동 버튼 추가
=> SW-125 feat(login): Add closing login modal

app/diary/dashboard/BarChartCard.js, app/diary/dashboard/DonutChartCard.js
- 대시보드의 DonutChartCard 데이터 패칭 (이번 달 감정별 빈도 차트)
- BarChartCard의 지난 달 감정 통계 API 호출 시, request data인 `startDate, endDate 값 구하기` 변경
- BarChartCard, DonutChartCard의 옵션 값 변경
=> SW-130 feat(data-fetching): Add donut chart data-fetching on dashboard

app/diary/common/Editor.js, app/hooks/mutations/useDiaryDelete.js, app/hooks/mutations/useDiarySave.js
=> SW-135 feat(diary): Modify diary save/delete

app/ReactQueryWrapper.jsx, app/common/header/Profile.js, app/home/landing/page.jsx, app/hooks/mutations/useDiaryDelete.js, app/hooks/mutations/useDiarySave.js, app/hooks/mutations/useUserInfoUpdate.js, app/layout.jsx
* 일기 생성/수정시 error catch 조건 수정 (생성-201/수정-200)
* 일기 생성/수정/삭제 onError에 invalidation 추가
* react-query 전체 감싸는 wrapper 하나만 사용하도록 수정
* react-query 공통 onError 실행 순서 변경 - 로그아웃 반복 해결
* 배경 이미지 resize
=> SW-135 fix(error handling): Fix & Add error handling

README.md, app/common/Drawer.jsx, app/common/header/Header.jsx, app/common/header/Login.js, app/common/header/Profile.js, app/diary/common/Editor.js, app/diary/common/backButton.js, app/diary/dashboard/BarChartCard.js, app/diary/dashboard/DonutChartCard.js, app/diary/dashboard/ProfileCard.js, app/diary/dashboard/RecentDiaryCard.js, app/diary/list/DateRangePicker.js, app/diary/list/ViewTypeTab.js, app/diary/list/calendar/calendarList.js, app/diary/list/grid/gridList.js, app/home/landing/page.jsx, app/hooks/mutations/useLogin.js, cypress.config.js, cypress/e2e/diary/diaryEdit.cy.js, cypress/e2e/diary/diaryList.cy.js, cypress/e2e/diary/diarySave.cy.js, cypress/e2e/member/userInfo.cy.js, cypress/e2e/member/userLogin.cy.js, cypress/fixtures/example.json, cypress/support/commands.js, cypress/support/e2e.js, next.config.js, package.json
* **Cypress를 통한 E2E 테스트 추가**
* Assertion 선택 오류 방지를 위한 **`data-cy`** attribute 추가
* 📁 `/cypress/e2e` 내부에 기능별 테스트 spec 추가
* README 파일 수정
=> SW-140 Add E2E Test

app/common/Drawer.jsx, app/common/header/Header.jsx, app/common/header/Login.js, app/common/header/Profile.js, app/diary/common/Editor.js, app/diary/common/backButton.js, app/diary/dashboard/BarChartCard.js, app/diary/dashboard/DonutChartCard.js, app/diary/dashboard/ProfileCard.js, app/diary/dashboard/RecentDiaryCard.js, app/diary/list/DateRangePicker.js, app/diary/list/ViewTypeTab.js, app/diary/list/calendar/calendarList.js, app/diary/list/grid/gridList.js, app/home/landing/page.jsx, cypress/e2e/diary/diaryEdit.cy.js, cypress/e2e/diary/diaryList.cy.js, cypress/e2e/diary/diarySave.cy.js, cypress/e2e/member/userInfo.cy.js, cypress/e2e/member/userLogin.cy.js, next.config.js, package.json
=> SW-142 Modify E2E Test

.github/workflows/github-action.yml, package.json
1. Jest 단위 테스트 추가
1. jest 실행 명령 `npm jest`에서 `npm test`로 변경
2. main branch일 때만 Cypress E2E 테스트 실행되도록 수정
3. main branch일 때만 Jaksim31-Front-CD 실행되도록 수정
=> SW-148 feat(test): Update github-action.yml

app/common/Tutorial.js, app/common/header/Login.js, app/common/header/Profile.js, app/diary/create/[date]/createDiary.js, app/diary/dashboard/ProfileCard.js, app/diary/dashboard/RecentDiaryCard.js, app/diary/dashboard/page.jsx, app/diary/list/calendar/calendarList.js, app/diary/list/grid/gridList.js, app/home/landing/ExampleScreen.js
1. next/image 이미지 사이즈 지정
2. next/link `prefetch=false` 옵션 추가
3. 대시보드 최근 일기 카드의 썸네일 크기 고정
1. console.log 삭제
2. react-query userInfo init 삭제
=> SW-142 feat(performance): Change to optimize performance

app/ExampleScreen.js, app/layout.jsx, app/page.jsx
copy landing page to main page
=> Modify main page (base url)

app/diary/dashboard/BarChartCard.js, app/diary/dashboard/DonutChartCard.js
=> Fix(dashboard): Modify emotion statics data fetching
